// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolVrAuthApi.Models;

namespace SchoolVrAuthApi.Migrations
{
    [DbContext(typeof(AuthContext))]
    partial class AuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolVrAuthApi.Models.LicenseKey", b =>
                {
                    b.Property<string>("LicenseKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(25)");

                    b.Property<bool>("IsActive");

                    b.Property<int>("NumOfMacAddressesAllowed");

                    b.Property<string>("UserId");

                    b.HasKey("LicenseKeyId");

                    b.HasIndex("UserId");

                    b.ToTable("LicenseKeys");
                });

            modelBuilder.Entity("SchoolVrAuthApi.Models.MacAddress", b =>
                {
                    b.Property<string>("MacAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime?>("AssignedDt")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("LicenseKeyId");

                    b.HasKey("MacAddressId");

                    b.HasIndex("LicenseKeyId");

                    b.ToTable("MacAddresses");
                });

            modelBuilder.Entity("SchoolVrAuthApi.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SchoolVrAuthApi.Models.LicenseKey", b =>
                {
                    b.HasOne("SchoolVrAuthApi.Models.User", "User")
                        .WithMany("LicenseKeys")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SchoolVrAuthApi.Models.MacAddress", b =>
                {
                    b.HasOne("SchoolVrAuthApi.Models.LicenseKey", "LicenseKey")
                        .WithMany("MacAddresses")
                        .HasForeignKey("LicenseKeyId");
                });
#pragma warning restore 612, 618
        }
    }
}
